// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ArticleItem: typeof import('./src/components/article-item/article-item.vue')['default']
    ArticlePie: typeof import('./src/components/charts/article-pie.vue')['default']
    'ArticlePie copy': typeof import('./src/components/charts/article-pie copy.vue')['default']
    ATable: typeof import('ant-design-vue/es')['Table']
    CardBreadnav: typeof import('./src/components/card-main/card-breadnav.vue')['default']
    CardFeature: typeof import('./src/components/card-main/card-feature.vue')['default']
    CategoryItem: typeof import('./src/components/category-item/index.vue')['default']
    CommentPie: typeof import('./src/components/charts/comment-pie.vue')['default']
    EmptyWrap: typeof import('./src/components/empty-wrap/index.vue')['default']
    FoldSideBar: typeof import('./src/components/side-bar/fold-side-bar.vue')['default']
    MdPreview: typeof import('./src/components/md-preview/index.vue')['default']
    NavBar: typeof import('./src/components/nav-bar/index.vue')['default']
    PageviewsBar: typeof import('./src/components/charts/pageviews-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/side-bar/index.vue')['default']
    SiderBar: typeof import('./src/components/side-bar/sider-bar.vue')['default']
    TextArea: typeof import('./src/components/text-area/index.vue')['default']
    TopArticle: typeof import('./src/components/charts/top-article.vue')['default']
    UserItem: typeof import('./src/components/user-item/user-item.vue')['default']
  }
}

export {}
