// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./src/components/article-item/article-item.vue')['default']
    ArticlePie: typeof import('./src/components/charts/article-pie.vue')['default']
    CardBreadnav: typeof import('./src/components/card-main/card-breadnav.vue')['default']
    CardFeature: typeof import('./src/components/card-main/card-feature.vue')['default']
    CommentPie: typeof import('./src/components/charts/comment-pie.vue')['default']
    EmptyWrap: typeof import('./src/components/empty-wrap/index.vue')['default']
    FoldSideBar: typeof import('./src/components/side-bar/fold-side-bar.vue')['default']
    MdPreview: typeof import('./src/components/md-preview/index.vue')['default']
    NavBar: typeof import('./src/components/nav-bar/index.vue')['default']
    PageviewsBar: typeof import('./src/components/charts/pageviews-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/side-bar/index.vue')['default']
    TextArea: typeof import('./src/components/text-area/index.vue')['default']
    TopArticle: typeof import('./src/components/charts/top-article.vue')['default']
  }
}

export {}
