version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    branches:
      only:
        - main
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f4:8f:70:b2:8b:48:24:40:09:7f:ca:4c:5e:ea:87:ba"
      - checkout
      - restore_cache:
          keys: 
            - dependencies_circle_node
      - run:
          name: Install
          command: pnpm install
      - save_cache:
          key: dependencies_circle_node
          paths:
            - node_modules
      - run:
          name: Build
          command: pnpm run build
